# Generated by Django 2.1.4 on 2018-12-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
